import marimo

__generated_with = "0.23.16"
app = marimo.App(width="wide")


@app.cell
def _():
    import sys
    import warnings
    from pathlib import Path
    from typing import Any, Callable, Dict, List, Optional, Tuple, Union

    # Ensure repository root is in sys.path
    repo_root = (
        Path(__file__).resolve().parents[1] if "__file__" in locals() else Path.cwd()
    )
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

    # Graceful sibling import for MV-HDBSCAN
    sibling_mv = repo_root.parent / "MV-HDBSCAN" / "src"
    if not sibling_mv.exists():
        sibling_mv = Path("../MV-HDBSCAN/src").resolve()

    if sibling_mv.exists() and str(sibling_mv) not in sys.path:
        sys.path.insert(0, str(sibling_mv))

    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
    import polars as pl
    import seaborn as sns
    from scipy.spatial.distance import cdist, pdist, squareform
    from scipy.stats import spearmanr
    from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score
    from sklearn.preprocessing import normalize

    # Project imports from CA-BERTopic
    from src.data import process_metadata
    from src.decoupled_kmeans import DecoupledMultiviewKMeans
    from src.decoupled_spectral import DecoupledMultiviewSpectralClustering

    try:
        from mv_hdbscan import MultiViewHDBSCAN

        has_mv_hdbscan = True
    except ImportError:
        MultiViewHDBSCAN = None
        has_mv_hdbscan = False

    # Configure plot styling
    sns.set_theme(style="whitegrid", palette="deep")
    plt.rcParams.update(
        {
            "font.sans-serif": "DejaVu Sans",
            "font.family": "sans-serif",
            "figure.titlesize": 13,
            "axes.titlesize": 11,
            "axes.labelsize": 10,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "legend.fontsize": 9,
            "figure.dpi": 130,
        }
    )

    return (
        Any,
        Callable,
        DecoupledMultiviewKMeans,
        DecoupledMultiviewSpectralClustering,
        Dict,
        List,
        MultiViewHDBSCAN,
        Optional,
        Path,
        Tuple,
        Union,
        cdist,
        has_mv_hdbscan,
        mo,
        normalize,
        np,
        pdist,
        pd,
        pl,
        plt,
        process_metadata,
        sns,
        spearmanr,
        squareform,
        sys,
        warnings,
        adjusted_rand_score,
        normalized_mutual_info_score,
    )


@app.cell
def _(has_mv_hdbscan, mo):
    mv_badge = (
        "🟢 **`MultiViewHDBSCAN` detected & loaded** from `../MV-HDBSCAN/src`"
        if has_mv_hdbscan
        else "🟡 **`MultiViewHDBSCAN` not found in `../MV-HDBSCAN`** (using standalone reachability fusion fallback)"
    )

    header = mo.md(
        rf"""
        # 📐 Methodological Exploration: Distance Metrics & Cross-View Scale in Multi-View Clustering
        ### Master's Thesis Research Notebook — *Covariate-Assisted Topic Modeling (CAST)*

        ---

        ### 🎯 Core Methodological Question
        > **"If two views produce distance distributions on very different numerical scales, can one view have more influence on multi-view clustering merely because its distances are numerically larger?"**

        In Covariate-Assisted Topic Modeling (CAST), documents possess two heterogeneous modalities:
        1. **Textual Semantic Embeddings (View 0):** High-dimensional, directionally oriented vectors generated by Sentence Transformers (`all-MiniLM-L6-v2`). Semantic relatedness is governed by **angular orientation (Cosine distance)**.
        2. **Tabular Document Metadata / Covariates (View 1):** Continuous or categorical attributes (e.g., star ratings, survey respondent age, education, political party). Empirical similarity is governed by **magnitude in Cartesian space (Euclidean distance)**.

        ### 🔍 Repository Architecture Context
        | Multi-View Model | Distance Interaction Mechanism | Theoretical Scale Sensitivity |
        | :--- | :--- | :--- |
        | **`MultiViewHDBSCAN`** (`../MV-HDBSCAN`) | Core-distance & mutual reachability fusion: $d_{{\text{{mreach}}}}(i,j) = \max(r_i, r_j, d_{{ij}})$. Built-in `scale_views=True` normalizes by $P_{{95}}(D)$. | **Sensitive when `scale_views=False`** (larger scale dominates reachability graph); **Invariant when `scale_views=True`**. |
        | **`DecoupledMultiviewKMeans`** (`src/decoupled_kmeans.py`) | Additive assignment distance: $D_{{\text{{total}}}} = w_0 D_{{\cos}}(x_0, c_0) + w_1 D_{{\text{{euc}}}}(x_1, c_1)$. | **Highly Sensitive**: if $D_{{\text{{euc}}}} \gg D_{{\cos}}$, metadata completely dictates cluster assignments. |
        | **`DecoupledMultiviewSpectralClustering`** (`src/decoupled_spectral.py`) | Kernel affinity fusion: Cosine similarity on text, Gaussian RBF $K = \exp\left(-\frac{{d^2}}{{2 \cdot \text{{med}}^2}}\right)$ on metadata. | **Scale-Invariant under $X \to cX$**: Median bandwidth heuristic automatically self-normalizes scale. |
        | **`AppendUMAP`** (`src/append_umap.py`) | Concatenates $[X_{{\text{{text}}}}, X_{{\text{{meta}}}}]$ before dimensionality reduction. | **Highly Sensitive**: vector norms dictate cosine dot product weighting. |

        ---
        {mv_badge}
        """
    )
    return (header,)


@app.cell
def _(mo):
    # Interactive parameter controls
    dataset_dropdown = mo.ui.dropdown(
        options=[
            "ANES (American National Election Study 2008)",
            "Synthetic Multiview Benchmark",
        ],
        value="ANES (American National Election Study 2008)",
        label="Dataset:",
    )

    sample_size_slider = mo.ui.slider(
        start=100,
        stop=1000,
        step=50,
        value=350,
        label="Sample Size (N):",
    )

    k_slider = mo.ui.slider(
        start=3,
        stop=30,
        step=1,
        value=10,
        label="k-NN / min_samples (k):",
    )

    scale_factor_select = mo.ui.dropdown(
        options=["0.1", "0.5", "1.0", "2.0", "5.0", "10.0", "50.0", "100.0"],
        value="10.0",
        label="Metadata Scale Factor (c):",
    )

    controls_panel = mo.vstack(
        [
            mo.md("### ⚙️ Interactive Controls"),
            mo.hstack(
                [dataset_dropdown, sample_size_slider, k_slider, scale_factor_select],
                justify="start",
                gap=2,
            ),
        ]
    )
    return (
        controls_panel,
        dataset_dropdown,
        k_slider,
        sample_size_slider,
        scale_factor_select,
    )


@app.cell
def _(
    Path,
    dataset_dropdown,
    mo,
    normalize,
    np,
    pl,
    process_metadata,
    sample_size_slider,
):
    # Load or generate representative representations
    _selected_ds = dataset_dropdown.value
    _n = sample_size_slider.value
    _rng = np.random.RandomState(42)

    _anes_path = Path("data/processed/anes_embeddings.parquet")
    _is_real = False
    _meta_columns = []

    if "ANES" in _selected_ds and _anes_path.exists():
        try:
            _raw_df = pl.read_parquet(_anes_path)
            # Filter empty texts if any
            _clean_df = _raw_df.filter(pl.col("clean_text").str.strip_chars() != "")
            if len(_clean_df) > _n:
                _sub_df = _clean_df.sample(n=_n, seed=42)
            else:
                _sub_df = _clean_df

            # Precomputed embeddings are 384-d dense unit vectors
            X_text_raw = np.array(
                _sub_df["clean_text_embedding"].to_list(), dtype=np.float64
            )

            # Metadata covariates processed using thesis pipeline
            _cov_config = {
                "numerical": ["years_of_education", "age"],
                "categorical": ["party_id"],
                "binary": [],
            }
            _meta_pl = process_metadata(_sub_df, _cov_config)
            X_meta_raw = _meta_pl.to_numpy().astype(np.float64)
            _meta_columns = _meta_pl.columns
            _is_real = True
            dataset_name = "ANES (2008 Political Survey)"
        except Exception:
            _is_real = False

    if not _is_real:
        # High-quality synthetic multi-view generator
        # View 0: 64-dim spherical Gaussian mixture (semantic embeddings)
        # View 1: 5-dim continuous tabular metadata with distinct clusters
        dataset_name = "Synthetic Multiview Benchmark (Simulated Semantic + Tabular)"
        _n_clusters = 4
        _pts_per_c = _n // _n_clusters
        _views_0, _views_1 = [], []

        for c_idx in range(_n_clusters):
            _center_0 = _rng.randn(64)
            _pts_0 = _center_0 + 0.3 * _rng.randn(_pts_per_c, 64)
            _views_0.append(_pts_0)

            _center_1 = _rng.uniform(0.0, 1.0, size=5) * (c_idx + 1)
            _pts_1 = _center_1 + 0.1 * _rng.randn(_pts_per_c, 5)
            _views_1.append(_pts_1)

        X_text_raw = np.vstack(_views_0)
        X_meta_raw = np.vstack(_views_1)
        _meta_columns = [f"meta_dim_{i}" for i in range(5)]

    # Strictly unit-normalize text representation as is standard for Sentence Transformers
    X_text = normalize(X_text_raw, norm="l2")
    X_meta = X_meta_raw.copy()

    _actual_n = X_text.shape[0]
    _text_dim = X_text.shape[1]
    _meta_dim = X_meta.shape[1]

    data_summary = mo.hstack(
        [
            mo.stat(
                value=f"{_actual_n}",
                label="Observations (N)",
                caption=f"Active sample: {_actual_n}",
            ),
            mo.stat(
                value=f"{_text_dim}D",
                label="Text View Dim",
                caption="Unit L2-normalized embeddings",
            ),
            mo.stat(
                value=f"{_meta_dim}D",
                label="Metadata View Dim",
                caption="MinMax continuous + one-hot",
            ),
            mo.stat(
                value=f"{'Real ANES' if _is_real else 'Synthetic'}",
                label="Data Source",
                caption=dataset_name,
            ),
        ],
        justify="start",
        gap=2,
    )

    return (
        X_meta,
        X_text,
        data_summary,
        dataset_name,
    )


@app.cell
def _(controls_panel, data_summary, mo):
    view_data_panel = mo.vstack(
        [
            controls_panel,
            mo.md("---"),
            data_summary,
        ]
    )
    return (view_data_panel,)


@app.cell
def _(X_meta, X_text, cdist, np, pdist, squareform):
    # Pairwise distance matrices computation
    # 1. Text View: Cosine Distance
    # np.clip guards against float precision quirks where cosine distance is slightly < 0
    _d_cos_vec = np.clip(pdist(X_text, metric="cosine"), 0.0, 2.0)
    D_text_cos = squareform(_d_cos_vec)
    np.fill_diagonal(D_text_cos, 0.0)

    # 2. Text View: Euclidean Distance
    _d_euc_vec = pdist(X_text, metric="euclidean")
    D_text_euc = squareform(_d_euc_vec)
    np.fill_diagonal(D_text_euc, 0.0)

    # 3. Metadata View: Euclidean Distance (standard Cartesian distance)
    _d_meta_euc_vec = pdist(X_meta, metric="euclidean")
    D_meta_euc = squareform(_d_meta_euc_vec)
    np.fill_diagonal(D_meta_euc, 0.0)

    # 4. Metadata View: Cosine Distance (to demonstrate directional distortion on tabular data)
    _d_meta_cos_vec = np.clip(pdist(X_meta, metric="cosine"), 0.0, 2.0)
    D_meta_cos = squareform(_d_meta_cos_vec)
    np.fill_diagonal(D_meta_cos, 0.0)

    # Helper function to extract strictly off-diagonal unique distances
    def get_off_diagonal_dists(D: np.ndarray) -> np.ndarray:
        _n_samples = D.shape[0]
        _i_idx, _j_idx = np.triu_indices(_n_samples, k=1)
        return D[_i_idx, _j_idx]

    off_text_cos = get_off_diagonal_dists(D_text_cos)
    off_text_euc = get_off_diagonal_dists(D_text_euc)
    off_meta_euc = get_off_diagonal_dists(D_meta_euc)
    off_meta_cos = get_off_diagonal_dists(D_meta_cos)

    return (
        D_meta_cos,
        D_meta_euc,
        D_text_cos,
        D_text_euc,
        get_off_diagonal_dists,
        off_meta_cos,
        off_meta_euc,
        off_text_cos,
        off_text_euc,
    )


@app.cell
def _(D_text_cos, D_text_euc, mo, np, plt, spearmanr):
    # Section 1: Monotonicity Sanity Check (Cosine vs Euclidean on L2-normalized Text)
    # Theory: For unit vectors u, v where ||u|| = ||v|| = 1:
    # ||u - v||^2 = ||u||^2 + ||v||^2 - 2(u . v) = 1 + 1 - 2 cos(u, v) = 2(1 - cos(u, v)) = 2 d_cos(u, v)
    # Therefore: d_euc = sqrt(2 * d_cos) and d_euc^2 = 2 * d_cos.

    _n_samples = D_text_cos.shape[0]
    _i_idx, _j_idx = np.triu_indices(_n_samples, k=1)

    _d_cos = D_text_cos[_i_idx, _j_idx]
    _d_euc = D_text_euc[_i_idx, _j_idx]
    _d_euc_sq = _d_euc**2
    _two_d_cos = 2.0 * _d_cos

    # Numerical difference
    _abs_diff = np.abs(_d_euc_sq - _two_d_cos)
    _max_diff = float(np.max(_abs_diff))
    _mean_diff = float(np.mean(_abs_diff))

    # Nearest-neighbor ranking equivalence check
    # Exclude self-distance by filling diagonal with infinity
    _D_cos_no_diag = D_text_cos.copy()
    _D_euc_no_diag = D_text_euc.copy()
    np.fill_diagonal(_D_cos_no_diag, np.inf)
    np.fill_diagonal(_D_euc_no_diag, np.inf)

    _nn_cos_1 = np.argmin(_D_cos_no_diag, axis=1)
    _nn_euc_1 = np.argmin(_D_euc_no_diag, axis=1)
    _fraction_top1_match = float(np.mean(_nn_cos_1 == _nn_euc_1))

    # Top-5 overlap check
    _top5_cos = np.argsort(_D_cos_no_diag, axis=1)[:, :5]
    _top5_euc = np.argsort(_D_euc_no_diag, axis=1)[:, :5]
    _top5_overlaps = [
        len(set(_top5_cos[row]).intersection(set(_top5_euc[row]))) / 5.0
        for row in range(_n_samples)
    ]
    _mean_top5_overlap = float(np.mean(_top5_overlaps))

    # Overall Spearman rank correlation
    _spearman_rho, _ = spearmanr(_d_cos, _d_euc)

    # Plot verification
    _fig, _axs = plt.subplots(1, 2, figsize=(11, 4.2))

    # Subplot A: d_euc^2 vs 2 * d_cos
    _axs[0].scatter(
        _two_d_cos[:2500],
        _d_euc_sq[:2500],
        alpha=0.35,
        s=10,
        color="#1f77b4",
        edgecolors="none",
    )
    _max_val = max(float(np.max(_two_d_cos)), float(np.max(_d_euc_sq)))
    _axs[0].plot(
        [0, _max_val],
        [0, _max_val],
        color="#d62728",
        linestyle="--",
        lw=1.5,
        label=r"Exact: $d_E^2 = 2 d_{\cos}$",
    )
    _axs[0].set_title(
        r"Monotonic Identity: $d_E^2$ vs $2 \cdot d_{\cos}$", fontweight="bold"
    )
    _axs[0].set_xlabel(r"$2 \cdot d_{\cos}(u, v)$")
    _axs[0].set_ylabel(r"$d_E(u, v)^2$")
    _axs[0].legend(loc="upper left")

    # Subplot B: Residual error distribution
    _axs[1].hist(_abs_diff, bins=40, color="#2ca02c", alpha=0.75, edgecolor="black")
    _axs[1].set_title("Floating-Point Precision Residuals", fontweight="bold")
    _axs[1].set_xlabel(r"Absolute Residual $|d_E^2 - 2 d_{\cos}|$")
    _axs[1].set_ylabel("Pairwise Count")
    _axs[1].ticklabel_format(style="sci", axis="x", scilimits=(0, 0))

    _fig.tight_layout()

    monotonicity_view = mo.vstack(
        [
            mo.md(
                r"""
            ## 1. Metric Choice Within a Normalized Representation: Cosine vs. Euclidean

            For any two unit-normalized vectors $u, v \in \mathbb{R}^d$ where $\|u\|_2 = \|v\|_2 = 1$:
            $$\|u - v\|_2^2 = \|u\|_2^2 + \|v\|_2^2 - 2(u \cdot v) = 1 + 1 - 2\cos(u, v) = 2(1 - \cos(u, v)) = 2 d_{\cos}(u, v)$$

            Therefore:
            $$d_E(u, v) = \sqrt{2 \cdot d_{\cos}(u, v)}$$

            Because $f(z) = \sqrt{2z}$ is strictly monotonically increasing for $z \ge 0$, **the nearest-neighbor rankings are identical**.
            """
            ),
            mo.hstack(
                [
                    mo.stat(
                        value=f"{_spearman_rho:.6f}",
                        label="Spearman Rank Correlation",
                        caption="Target: 1.000000",
                    ),
                    mo.stat(
                        value=f"{_fraction_top1_match * 100:.1f}%",
                        label="Identical 1-NN Match",
                        caption="Exact neighbor identity",
                    ),
                    mo.stat(
                        value=f"{_mean_top5_overlap * 100:.1f}%",
                        label="Top-5 Neighbor Overlap",
                        caption="Shared 5-nearest neighbors",
                    ),
                    mo.stat(
                        value=f"{_max_diff:.2e}",
                        label="Max Numerical Error",
                        caption="IEEE 754 precision limit",
                    ),
                ],
                justify="start",
                gap=2,
            ),
            mo.as_html(_fig),
            mo.md(
                """
            > **Methodological Takeaway**: Within a normalized semantic text representation, switching between Cosine and Euclidean
            > distance is a monotonic transformation of the exact same geometry. Nearest-neighbor graphs remain identical,
            > even though raw numerical distance values change.
            """
            ),
        ]
    )
    return (monotonicity_view,)


@app.cell
def _(
    mo,
    np,
    off_meta_cos,
    off_meta_euc,
    off_text_cos,
    off_text_euc,
    pd,
    plt,
    sns,
):
    # Section 2: Global Distance Distributions & ECDFs across Heterogeneous Views
    # Build robust summary table for all off-diagonal pairwise distances
    _views_data = {
        "Text View (Cosine)": off_text_cos,
        "Text View (Euclidean)": off_text_euc,
        "Metadata View (Euclidean)": off_meta_euc,
        "Metadata View (Cosine)": off_meta_cos,
    }

    _records = []
    for _name, _arr in _views_data.items():
        _p5, _p25, _p50, _p75, _p95 = np.percentile(_arr, [5, 25, 50, 75, 95])
        _records.append(
            {
                "Modality / Metric": _name,
                "Pairs (N)": f"{len(_arr):,}",
                "Mean": f"{np.mean(_arr):.4f}",
                "Std": f"{np.std(_arr):.4f}",
                "Min": f"{np.min(_arr):.4f}",
                "5th %": f"{_p5:.4f}",
                "25th % (Q1)": f"{_p25:.4f}",
                "Median": f"{_p50:.4f}",
                "75th % (Q3)": f"{_p75:.4f}",
                "95th %": f"{_p95:.4f}",
                "Max": f"{np.max(_arr):.4f}",
                "IQR": f"{(_p75 - _p25):.4f}",
            }
        )

    summary_df = pd.DataFrame(_records)

    # Publication-ready ECDF and KDE visualization
    _fig, _axs = plt.subplots(1, 2, figsize=(12, 4.4))

    _colors = {
        "Text View (Cosine)": "#1f77b4",
        "Text View (Euclidean)": "#2ca02c",
        "Metadata View (Euclidean)": "#d62728",
        "Metadata View (Cosine)": "#9467bd",
    }

    for _name, _arr in _views_data.items():
        _sorted = np.sort(_arr)
        _ecdf = np.arange(1, len(_sorted) + 1) / len(_sorted)
        _axs[0].plot(_sorted, _ecdf, label=_name, color=_colors[_name], lw=2.0)
        sns.kdeplot(
            _arr, ax=_axs[1], label=_name, color=_colors[_name], lw=1.8, bw_adjust=0.8
        )

    _axs[0].set_title(
        "Empirical Cumulative Distribution Functions (ECDF)", fontweight="bold"
    )
    _axs[0].set_xlabel("Pairwise Distance Value")
    _axs[0].set_ylabel("Cumulative Probability P(D ≤ d)")
    _axs[0].legend(loc="lower right")
    _axs[0].grid(True, linestyle=":", alpha=0.6)

    _axs[1].set_title("Probability Density Estimation (KDE)", fontweight="bold")
    _axs[1].set_xlabel("Pairwise Distance Value")
    _axs[1].set_ylabel("Density")
    _axs[1].legend(loc="upper right")
    _axs[1].grid(True, linestyle=":", alpha=0.6)

    _fig.tight_layout()

    global_dists_view = mo.vstack(
        [
            mo.md(
                r"""
            ## 2. Scale Across Heterogeneous Views: Global Distance Distributions

            While Cosine and Euclidean distances are monotonically linked within the text view, **distances between text and metadata live in completely different worlds**:
            * **Text Cosine distances** are naturally bounded in $[0, 2]$ and typically concentrated tightly around $0.4 - 0.9$.
            * **Metadata Euclidean distances** depend on feature count, coordinate variance, and raw scaling. Even with Min-Max normalization, the maximum Euclidean distance in $d$ dimensions is $\sqrt{d}$.
            """
            ),
            mo.ui.table(summary_df),
            mo.as_html(_fig),
            mo.md(
                """
            > **Observation**: Notice the separation between the Text Cosine curve and the Metadata Euclidean curve.
            > In additive multi-view frameworks, if one curve sits significantly to the right of the other,
            > that view will mechanically dominate distance-based decisions.
            """
            ),
        ]
    )
    return (global_dists_view,)


@app.cell
def _(
    D_meta_euc,
    D_text_cos,
    D_text_euc,
    k_slider,
    mo,
    np,
    pd,
    plt,
    sns,
):
    # Section 3: Local-Neighborhood & Core-Distance Scale
    # In HDBSCAN, the core distance r_{i, k} is defined as the distance from sample i
    # to its k-th nearest neighbor (with min_samples = k).
    _k = k_slider.value
    _n = D_text_cos.shape[0]
    _effective_k = min(max(1, _k), _n - 1)

    def extract_knn_distances(D: np.ndarray, k: int) -> np.ndarray:
        # Exclude self distance (diagonal is 0.0)
        _sorted = np.sort(D, axis=1)
        # Column 0 is self distance 0.0; column k is the k-th nearest neighbor distance
        return _sorted[:, k]

    knn_text_cos = extract_knn_distances(D_text_cos, _effective_k)
    knn_text_euc = extract_knn_distances(D_text_euc, _effective_k)
    knn_meta_euc = extract_knn_distances(D_meta_euc, _effective_k)

    _knn_records = [
        {
            "View / Metric": "Text (Cosine)",
            "k": _effective_k,
            "Mean": f"{np.mean(knn_text_cos):.4f}",
            "Std": f"{np.std(knn_text_cos):.4f}",
            "Min": f"{np.min(knn_text_cos):.4f}",
            "Median": f"{np.median(knn_text_cos):.4f}",
            "Max": f"{np.max(knn_text_cos):.4f}",
            "IQR": f"{(np.percentile(knn_text_cos, 75) - np.percentile(knn_text_cos, 25)):.4f}",
        },
        {
            "View / Metric": "Text (Euclidean)",
            "k": _effective_k,
            "Mean": f"{np.mean(knn_text_euc):.4f}",
            "Std": f"{np.std(knn_text_euc):.4f}",
            "Min": f"{np.min(knn_text_euc):.4f}",
            "Median": f"{np.median(knn_text_euc):.4f}",
            "Max": f"{np.max(knn_text_euc):.4f}",
            "IQR": f"{(np.percentile(knn_text_euc, 75) - np.percentile(knn_text_euc, 25)):.4f}",
        },
        {
            "View / Metric": "Metadata (Euclidean)",
            "k": _effective_k,
            "Mean": f"{np.mean(knn_meta_euc):.4f}",
            "Std": f"{np.std(knn_meta_euc):.4f}",
            "Min": f"{np.min(knn_meta_euc):.4f}",
            "Median": f"{np.median(knn_meta_euc):.4f}",
            "Max": f"{np.max(knn_meta_euc):.4f}",
            "IQR": f"{(np.percentile(knn_meta_euc, 75) - np.percentile(knn_meta_euc, 25)):.4f}",
        },
    ]
    knn_summary_df = pd.DataFrame(_knn_records)

    # Visualizing local neighborhood distances
    _fig, _axs = plt.subplots(1, 2, figsize=(12, 4.4))

    _knn_dict = {
        "Text (Cosine)": knn_text_cos,
        "Text (Euclidean)": knn_text_euc,
        "Metadata (Euclidean)": knn_meta_euc,
    }
    _knn_colors = ["#1f77b4", "#2ca02c", "#d62728"]

    # Subplot A: Boxplots of k-NN distance distributions
    _box_data = [knn_text_cos, knn_text_euc, knn_meta_euc]
    _box = _axs[0].boxplot(
        _box_data,
        tick_labels=["Text (Cosine)", "Text (Euclidean)", "Metadata (Euclidean)"],
        patch_artist=True,
        medianprops=dict(color="black", lw=1.8),
    )
    for _patch, _color in zip(_box["boxes"], _knn_colors):
        _patch.set_facecolor(_color)
        _patch.set_alpha(0.65)

    _axs[0].set_title(
        f"Local k-NN Distance Scale (k={_effective_k})", fontweight="bold"
    )
    _axs[0].set_ylabel("Distance to k-th Nearest Neighbor")
    _axs[0].grid(True, linestyle=":", alpha=0.6)

    # Subplot B: ECDF of core distances
    for (_lbl, _arr), _color in zip(_knn_dict.items(), _knn_colors):
        _s = np.sort(_arr)
        _e = np.arange(1, len(_s) + 1) / len(_s)
        _axs[1].plot(_s, _e, label=_lbl, color=_color, lw=2.0)

    _axs[1].set_title(
        f"ECDF of HDBSCAN Core Distances $r_{{i, {_effective_k}}}$", fontweight="bold"
    )
    _axs[1].set_xlabel("Core Distance Value")
    _axs[1].set_ylabel("Cumulative Fraction of Points")
    _axs[1].legend(loc="lower right")
    _axs[1].grid(True, linestyle=":", alpha=0.6)

    _fig.tight_layout()

    local_scale_view = mo.vstack(
        [
            mo.md(
                r"""
            ## 3. Local-Neighborhood Geometry & HDBSCAN Core Distances

            Because HDBSCAN is a **density-based** hierarchical algorithm, the critical quantity is **not** only pairwise distance,
            but the **local core distance**:
            $$r_{i, k}^{(v)} = d^{(v)}\left(i, \operatorname{kNN}_v(i, k)\right)$$

            In HDBSCAN's mutual reachability equation:
            $$d_{\text{mreach}}^{(v)}(i, j) = \max\left(r_{i, k}^{(v)}, r_{j, k}^{(v)}, d^{(v)}(i, j)\right)$$

            When multi-view algorithms fuse mutual reachability graphs across views (e.g. `MultiViewHDBSCAN` with $\text{fusion}=\text{"max"}$ or $\text{"mean"}$),
            a view with systematically higher core distances will inflate mutual reachability and dictate the minimum spanning tree!
            """
            ),
            mo.ui.table(knn_summary_df),
            mo.as_html(_fig),
        ]
    )
    return (
        extract_knn_distances,
        knn_meta_euc,
        knn_text_cos,
        knn_text_euc,
        local_scale_view,
    )


@app.cell
def _(X_meta, cdist, mo, np, pdist, plt, scale_factor_select, spearmanr):
    # Section 4: Metadata Scale Perturbation & Unit-Invariance Test
    # If a researcher measures metadata in grams vs kilograms, or standardizes vs doesn't,
    # the representation is rescaled: X_meta -> c * X_meta.
    # Under Euclidean distance: d_E(c*x, c*y) = |c| * d_E(x, y).
    # The geometric neighbor rankings are 100% invariant, but numerical distance changes by factor c.

    _c_chosen = float(scale_factor_select.value)
    _test_scales = [0.1, 1.0, 10.0, 100.0]

    _d_base = pdist(X_meta, metric="euclidean")
    _scale_results = []

    for _c in _test_scales:
        _X_scaled = _c * X_meta
        _d_scaled = pdist(_X_scaled, metric="euclidean")
        _rho, _ = spearmanr(_d_base, _d_scaled)
        _scale_ratio = np.mean(_d_scaled) / np.mean(_d_base)
        _scale_results.append(
            {
                "c": _c,
                "Mean Distance": np.mean(_d_scaled),
                "Median Distance": np.median(_d_scaled),
                "Scale Multiplier": _scale_ratio,
                "Spearman Rank Invariance": _rho,
            }
        )

    # Plot scale perturbation boxplots
    _fig, _axs = plt.subplots(1, 2, figsize=(12, 4.4))

    _dist_samples = [pdist(_c * X_meta, metric="euclidean") for _c in _test_scales]
    _box = _axs[0].boxplot(
        _dist_samples,
        tick_labels=[f"c={_c}" for _c in _test_scales],
        patch_artist=True,
        medianprops=dict(color="black", lw=1.8),
    )
    _colors = ["#6baed6", "#3182bd", "#08519c", "#08306b"]
    for _patch, _col in zip(_box["boxes"], _colors):
        _patch.set_facecolor(_col)
        _patch.set_alpha(0.7)

    _axs[0].set_yscale("log")
    _axs[0].set_title(
        "Metadata Pairwise Distance Distribution vs Scale Factor c", fontweight="bold"
    )
    _axs[0].set_xlabel("Scale Factor c (Logarithmic Y-axis)")
    _axs[0].set_ylabel("Pairwise Euclidean Distance (log scale)")
    _axs[0].grid(True, linestyle=":", alpha=0.6)

    # Subplot B: Rank invariance demonstration
    _d_1 = pdist(X_meta, metric="euclidean")[:1500]
    _d_c = pdist(_c_chosen * X_meta, metric="euclidean")[:1500]
    _axs[1].scatter(_d_1, _d_c, alpha=0.4, s=12, color="#08519c")
    _axs[1].plot(
        [0, max(_d_1)],
        [0, _c_chosen * max(_d_1)],
        color="#d62728",
        linestyle="--",
        lw=1.5,
        label=f"Exact Linear Slope: {_c_chosen:.1f}",
    )
    _axs[1].set_title(
        f"Rank Invariance Verification (c={_c_chosen:.1f})", fontweight="bold"
    )
    _axs[1].set_xlabel(r"Original Distance $d_E(x, y)$")
    _axs[1].set_ylabel(rf"Rescaled Distance $d_E(c x, c y)$ (c={_c_chosen})")
    _axs[1].legend(loc="upper left")
    _axs[1].grid(True, linestyle=":", alpha=0.6)

    _fig.tight_layout()

    scale_perturbation_view = mo.vstack(
        [
            mo.md(
                r"""
            ## 4. Metadata Scale Perturbation & Unit-Invariance Diagnostic

            Consider multiplying the metadata representation by a scalar $c$:
            $$X_{\text{meta}}^{(c)} = c \cdot X_{\text{meta}}, \quad c \in \{\text{0.1, 1.0, 10.0, 100.0}\}$$

            Under Euclidean distance:
            $$d_E(cx, cy) = \|cx - cy\|_2 = |c| \cdot \|x - y\|_2 = |c| \cdot d_E(x, y)$$

            * **Nearest-neighbor order correlation is exactly 1.000000**: not a single neighbor flips ranking.
            * **Distance scale expands by exactly $|c|$**.

            This diagnostic serves as the benchmark test:
            > **If a multi-view clustering algorithm drastically shifts its assignments when metadata is replaced with $10X$,
            > despite identical metadata neighbor rankings, the algorithm is sensitive to arbitrary scale/units.**
            """
            ),
            mo.as_html(_fig),
        ]
    )
    return (scale_perturbation_view,)


@app.cell
def _(
    DecoupledMultiviewKMeans,
    DecoupledMultiviewSpectralClustering,
    MultiViewHDBSCAN,
    X_meta,
    X_text,
    adjusted_rand_score,
    has_mv_hdbscan,
    mo,
    np,
    pd,
    plt,
):
    # Section 5: Empirical Downstream Multi-View Clustering Impact
    # We now directly test the hypothesis: Does scale mismatch cause one view to dominate?
    # We test 3 multi-view models across scale perturbations c in [0.1, 1.0, 10.0, 100.0]:
    # 1. MultiViewHDBSCAN with scale_views=False (unnormalized reachability)
    # 2. MultiViewHDBSCAN with scale_views=True (95th-percentile normalized reachability)
    # 3. DecoupledMultiviewKMeans (additive distance: w0 * d_cos + w1 * d_euc)
    # 4. DecoupledMultiviewSpectralClustering (median-bandwidth RBF kernel)

    _c_values = [0.1, 0.5, 1.0, 5.0, 10.0, 50.0, 100.0]
    _sub_n = min(300, X_text.shape[0])
    _X_t = X_text[:_sub_n]
    _X_m = X_meta[:_sub_n]

    # Baseline single-view clusterings for comparison
    # We fit single-view models to see whether multi-view output aligns with text or metadata
    _km_text_base = (
        DecoupledMultiviewKMeans(n_clusters=4, view_weights=[1.0, 0.0], random_state=42)
        .fit([_X_t, _X_m])
        .labels_
    )
    _km_meta_base = (
        DecoupledMultiviewKMeans(n_clusters=4, view_weights=[0.0, 1.0], random_state=42)
        .fit([_X_t, _X_m])
        .labels_
    )

    # Evaluate across scales
    _km_ari_text, _km_ari_meta = [], []
    _spec_ari_text, _spec_ari_meta = [], []
    _mvhdb_unscaled_ari_text, _mvhdb_unscaled_ari_meta = [], []
    _mvhdb_scaled_ari_text, _mvhdb_scaled_ari_meta = [], []

    # Single-view HDBSCAN baselines if available
    _hdb_text_base = None
    _hdb_meta_base = None
    if has_mv_hdbscan and MultiViewHDBSCAN is not None:
        try:
            _hdb_t = MultiViewHDBSCAN(
                metric="cosine", min_cluster_size=8, scale_views=False
            ).fit([_X_t])
            _hdb_m = MultiViewHDBSCAN(
                metric="euclidean", min_cluster_size=8, scale_views=False
            ).fit([_X_m])
            _hdb_text_base = _hdb_t.labels_
            _hdb_meta_base = _hdb_m.labels_
        except Exception:
            pass

    for _c in _c_values:
        _X_m_scaled = _c * _X_m

        # 1. DecoupledMultiviewKMeans
        try:
            _km = DecoupledMultiviewKMeans(
                n_clusters=4, view_weights=[1.0, 1.0], random_state=42
            ).fit([_X_t, _X_m_scaled])
            _km_ari_text.append(adjusted_rand_score(_km_text_base, _km.labels_))
            _km_ari_meta.append(adjusted_rand_score(_km_meta_base, _km.labels_))
        except Exception:
            _km_ari_text.append(np.nan)
            _km_ari_meta.append(np.nan)

        # 2. DecoupledMultiviewSpectralClustering
        try:
            _sc = DecoupledMultiviewSpectralClustering(
                n_clusters=4, random_state=42
            ).fit([_X_t, _X_m_scaled])
            _spec_ari_text.append(adjusted_rand_score(_km_text_base, _sc.labels_))
            _spec_ari_meta.append(adjusted_rand_score(_km_meta_base, _sc.labels_))
        except Exception:
            _spec_ari_text.append(np.nan)
            _spec_ari_meta.append(np.nan)

        # 3. MultiViewHDBSCAN (Unscaled vs Scaled)
        if _hdb_text_base is not None and _hdb_meta_base is not None:
            try:
                _mvh_u = MultiViewHDBSCAN(
                    metric=["cosine", "euclidean"],
                    scale_views=False,
                    min_cluster_size=8,
                    fusion="max",
                ).fit([_X_t, _X_m_scaled])
                _mvhdb_unscaled_ari_text.append(
                    adjusted_rand_score(_hdb_text_base, _mvh_u.labels_)
                )
                _mvhdb_unscaled_ari_meta.append(
                    adjusted_rand_score(_hdb_meta_base, _mvh_u.labels_)
                )
            except Exception:
                _mvhdb_unscaled_ari_text.append(np.nan)
                _mvhdb_unscaled_ari_meta.append(np.nan)

            try:
                _mvh_s = MultiViewHDBSCAN(
                    metric=["cosine", "euclidean"],
                    scale_views=True,
                    min_cluster_size=8,
                    fusion="max",
                ).fit([_X_t, _X_m_scaled])
                _mvhdb_scaled_ari_text.append(
                    adjusted_rand_score(_hdb_text_base, _mvh_s.labels_)
                )
                _mvhdb_scaled_ari_meta.append(
                    adjusted_rand_score(_hdb_meta_base, _mvh_s.labels_)
                )
            except Exception:
                _mvhdb_scaled_ari_text.append(np.nan)
                _mvhdb_scaled_ari_meta.append(np.nan)

    # Plot empirical sensitivity comparison
    _n_cols = 3 if (_hdb_text_base is not None) else 2
    _fig, _axs = plt.subplots(1, _n_cols, figsize=(5 * _n_cols, 4.4), sharey=True)

    # Subplot 1: Decoupled Multiview K-Means
    _axs[0].plot(
        _c_values,
        _km_ari_text,
        marker="o",
        lw=2,
        color="#1f77b4",
        label="ARI with Text-Alone",
    )
    _axs[0].plot(
        _c_values,
        _km_ari_meta,
        marker="s",
        lw=2,
        color="#d62728",
        label="ARI with Meta-Alone",
    )
    _axs[0].set_xscale("log")
    _axs[0].set_title(
        "Decoupled Multi-View K-Means\n(Additive Distance: $d_{\\cos} + d_{\\text{euc}}$)",
        fontweight="bold",
    )
    _axs[0].set_xlabel("Metadata Scale Factor c (log scale)")
    _axs[0].set_ylabel("Adjusted Rand Index (ARI)")
    _axs[0].legend(loc="best")
    _axs[0].grid(True, linestyle=":", alpha=0.6)

    # Subplot 2: Decoupled Multiview Spectral Clustering
    _axs[1].plot(
        _c_values,
        _spec_ari_text,
        marker="o",
        lw=2,
        color="#1f77b4",
        label="ARI with Text-Alone",
    )
    _axs[1].plot(
        _c_values,
        _spec_ari_meta,
        marker="s",
        lw=2,
        color="#d62728",
        label="ARI with Meta-Alone",
    )
    _axs[1].set_xscale("log")
    _axs[1].set_title(
        "Multi-View Spectral Clustering\n(Heuristic Median RBF Kernel)",
        fontweight="bold",
    )
    _axs[1].set_xlabel("Metadata Scale Factor c (log scale)")
    _axs[1].legend(loc="best")
    _axs[1].grid(True, linestyle=":", alpha=0.6)

    # Subplot 3: MultiView HDBSCAN (if available)
    if _n_cols == 3:
        _axs[2].plot(
            _c_values,
            _mvhdb_unscaled_ari_meta,
            marker="^",
            lw=2,
            linestyle="--",
            color="#d62728",
            label="Unscaled (scale_views=False)",
        )
        _axs[2].plot(
            _c_values,
            _mvhdb_scaled_ari_meta,
            marker="o",
            lw=2,
            linestyle="-",
            color="#2ca02c",
            label="Normalized (scale_views=True)",
        )
        _axs[2].set_xscale("log")
        _axs[2].set_title(
            "MultiView HDBSCAN Alignment\n(Agreement with Metadata View)",
            fontweight="bold",
        )
        _axs[2].set_xlabel("Metadata Scale Factor c (log scale)")
        _axs[2].legend(loc="best")
        _axs[2].grid(True, linestyle=":", alpha=0.6)

    _fig.tight_layout()

    empirical_impact_view = mo.vstack(
        [
            mo.md(
                r"""
            ## 5. Downstream Clustering Impact: Empirical Proof of Scale Domination

            This is the definitive methodological experiment. We track how cluster assignments shift as metadata is scaled by $c \in [0.1, 100.0]$:
            * In **`DecoupledMultiviewKMeans`**: At $c=0.1$, the text view dominates ($\text{ARI} \to 1$ with text). As $c$ increases to $10.0$ and $100.0$, the metadata distance completely overwhelms the cosine distance, driving ARI with metadata to near $1.0$.
            * In **`DecoupledMultiviewSpectralClustering`**: Because the Gaussian RBF kernel dynamically chooses $\gamma = \frac{1}{2 \cdot \text{median}(D)^2}$, the affinity matrix remains **strictly invariant** to scalar rescaling!
            * In **`MultiViewHDBSCAN`**: When `scale_views=False`, the larger-scale view mechanically takes over the mutual reachability graph. Enabling `scale_views=True` (normalizing by $P_{95}(D)$) effectively neutralizes arbitrary scaling, preserving multi-view synergy.
            """
            ),
            mo.as_html(_fig),
        ]
    )
    return (empirical_impact_view,)


@app.cell
def _(
    D_meta_euc,
    D_text_cos,
    get_off_diagonal_dists,
    mo,
    np,
    plt,
):
    # Section 6: Exploratory Distance Normalization Strategies
    # What happens when we normalize distance matrices before combining them?
    # Strategies:
    # 1. 95th-Percentile Normalization: D / P_95(D) (Used by MultiViewHDBSCAN)
    # 2. Median Normalization: D / median(D)
    # 3. Mean Normalization: D / mean(D)
    # 4. Max Normalization: D / max(D)

    _t_dists = get_off_diagonal_dists(D_text_cos)
    _m_dists = get_off_diagonal_dists(D_meta_euc)

    _norm_strategies = {
        "Raw (Unnormalized)": (_t_dists, _m_dists),
        "P95 Normalization (D / P95)": (
            _t_dists / np.percentile(_t_dists, 95),
            _m_dists / np.percentile(_m_dists, 95),
        ),
        "Median Normalization (D / Med)": (
            _t_dists / np.median(_t_dists),
            _m_dists / np.median(_m_dists),
        ),
        "Mean Normalization (D / Mean)": (
            _t_dists / np.mean(_t_dists),
            _m_dists / np.mean(_m_dists),
        ),
        "Max Normalization (D / Max)": (
            _t_dists / np.max(_t_dists),
            _m_dists / np.max(_m_dists),
        ),
    }

    _fig, _axs = plt.subplots(1, 5, figsize=(16, 3.8), sharey=True)

    for _idx, (_title, (_t_norm, _m_norm)) in enumerate(_norm_strategies.items()):
        _ax = _axs[_idx]
        _st = np.sort(_t_norm)
        _sm = np.sort(_m_norm)
        _et = np.arange(1, len(_st) + 1) / len(_st)
        _em = np.arange(1, len(_sm) + 1) / len(_sm)

        _ax.plot(_st, _et, label="Text (Cos)", color="#1f77b4", lw=2.0)
        _ax.plot(_sm, _em, label="Meta (Euc)", color="#d62728", lw=2.0)
        _ax.set_title(_title, fontsize=9.5, fontweight="bold")
        _ax.set_xlabel("Normalized Distance")
        if _idx == 0:
            _ax.set_ylabel("ECDF P(D ≤ d)")
        _ax.grid(True, linestyle=":", alpha=0.6)
        if _idx == 0:
            _ax.legend(loc="lower right")

    _fig.tight_layout()

    norm_view = mo.vstack(
        [
            mo.md(
                r"""
            ## 6. Exploratory Normalization Strategies

            To avoid mechanical scale domination in additive distance frameworks (`DecoupledMultiviewKMeans`, `AppendUMAP`, or unscaled `MultiViewHDBSCAN`),
            we can normalize distance matrices before fusion:

            1. **$P_{95}$ Normalization ($D / P_{95}(D)$)**: Used by `MultiViewHDBSCAN`. Robust against extreme outliers while mapping the bulk of distances into $[0, 1]$.
            2. **Median Normalization ($D / \operatorname{median}(D)$)**: Centers the typical distance around $1.0$. Highly robust against skewed tabular metadata.
            3. **Mean Normalization ($D / \mu(D)$)**: Aligns overall expectations, but vulnerable to heavy-tailed distributions.
            4. **Max Normalization ($D / \max(D)$)**: Forces strict bounds $[0, 1]$, but vulnerable to solitary rogue outliers compressing the entire distribution.
            """
            ),
            mo.as_html(_fig),
        ]
    )
    return (norm_view,)


@app.cell
def _(
    Any,
    Dict,
    extract_knn_distances,
    get_off_diagonal_dists,
    mo,
    np,
    pd,
    plt,
):
    # Section 7: Clean Reusable Hook for Arbitrary Distance Matrices
    # Allows researchers to plug in any real experimental distance matrices:
    # compare_distance_views({"text": D_text, "metadata": D_meta}, k=10)

    def compare_distance_views(
        distance_matrices: Dict[str, np.ndarray],
        k: int = 10,
        scale_percentile: float = 95.0,
    ) -> Dict[str, Any]:
        """Analyzes and compares arbitrary precomputed distance matrices across views.

        Parameters
        ----------
        distance_matrices : dict[str, np.ndarray]
            Dictionary mapping view name to a square, symmetric 2D distance matrix.
        k : int, default=10
            Neighborhood size for k-NN / core-distance extraction.
        scale_percentile : float, default=95.0
            Percentile for scale normalization.

        Returns
        -------
        dict[str, Any]
            Dictionary containing summary tables, stats, and Matplotlib figures.
        """
        _records = []
        _knn_records = []
        _n_views = len(distance_matrices)

        for _vname, _D in distance_matrices.items():
            _off = get_off_diagonal_dists(_D)
            _p5, _p25, _p50, _p75, _p95 = np.percentile(_off, [5, 25, 50, 75, 95])
            _records.append(
                {
                    "View": _vname,
                    "Mean": np.mean(_off),
                    "Median": _p50,
                    "Std": np.std(_off),
                    "Min": np.min(_off),
                    "95th %": _p95,
                    "Max": np.max(_off),
                    "IQR": _p75 - _p25,
                }
            )

            _knn = extract_knn_distances(_D, k=min(k, _D.shape[0] - 1))
            _knn_records.append(
                {
                    "View": _vname,
                    "k-NN Mean": np.mean(_knn),
                    "k-NN Median": np.median(_knn),
                    "k-NN IQR": np.percentile(_knn, 75) - np.percentile(_knn, 25),
                }
            )

        _global_df = pd.DataFrame(_records)
        _knn_df = pd.DataFrame(_knn_records)

        # Plot ECDFs
        _fig, _axs = plt.subplots(1, 2, figsize=(11, 4.0))
        for _vname, _D in distance_matrices.items():
            _off = get_off_diagonal_dists(_D)
            _s = np.sort(_off)
            _e = np.arange(1, len(_s) + 1) / len(_s)
            _axs[0].plot(_s, _e, label=_vname, lw=2)

            _knn = extract_knn_distances(_D, k=min(k, _D.shape[0] - 1))
            _sk = np.sort(_knn)
            _ek = np.arange(1, len(_sk) + 1) / len(_sk)
            _axs[1].plot(_sk, _ek, label=_vname, lw=2)

        _axs[0].set_title("Global Distance ECDF", fontweight="bold")
        _axs[0].set_xlabel("Pairwise Distance")
        _axs[0].set_ylabel("P(D ≤ d)")
        _axs[0].legend(loc="lower right")
        _axs[0].grid(True, linestyle=":", alpha=0.6)

        _axs[1].set_title(f"Local k-NN Core Distance ECDF (k={k})", fontweight="bold")
        _axs[1].set_xlabel("k-NN Distance")
        _axs[1].legend(loc="lower right")
        _axs[1].grid(True, linestyle=":", alpha=0.6)

        _fig.tight_layout()

        return {
            "global_summary": _global_df,
            "knn_summary": _knn_df,
            "figure": _fig,
        }

    hook_view = mo.vstack(
        [
            mo.md(
                """
            ## 7. Reusable Experimental Hook

            You can pass any custom square distance matrices directly into `compare_distance_views`:
            ```python
            results = compare_distance_views({
                "Sentence-BERT (Cosine)": D_text,
                "Demographics (Euclidean)": D_meta,
            }, k=10)
            ```
            """
            ),
        ]
    )
    return (
        compare_distance_views,
        hook_view,
    )


@app.cell
def _(
    empirical_impact_view,
    global_dists_view,
    header,
    hook_view,
    local_scale_view,
    mo,
    monotonicity_view,
    norm_view,
    scale_perturbation_view,
    view_data_panel,
):
    # Assembling the master layout
    dashboard = mo.vstack(
        [
            header,
            view_data_panel,
            mo.md("---"),
            monotonicity_view,
            mo.md("---"),
            global_dists_view,
            mo.md("---"),
            local_scale_view,
            mo.md("---"),
            scale_perturbation_view,
            mo.md("---"),
            empirical_impact_view,
            mo.md("---"),
            norm_view,
            mo.md("---"),
            hook_view,
        ]
    )
    dashboard
    return (dashboard,)


if __name__ == "__main__":
    app.run()
